/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dynamicconadminapp;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronnie
 */
public class Home extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    String [] MonthsArr = {"January","February","March","April","May","June","July","August","September","October","November","December"};
    /**
     * Creates new form Home
     */
    
    public Home(Connection con) {
        this.con = con;
        initComponents(); 
        firstExecute();
    }
    
    public void firstExecute(){
        UsernameLbl.setText(DynamicConAdminApp.CurrentUser);//TODO User
        setLocationRelativeTo(null);
        setBackground();
        
        Timer t = new Timer(1000, new Listener());
        t.start();
        
        ImageIcon imageIcon = new ImageIcon("../DynamicConAdminApp/src/Resources/LogIn.png"); 
        Image image = imageIcon.getImage(); 
        Image newimg = image.getScaledInstance(80, 80,  java.awt.Image.SCALE_SMOOTH); 
        imageIcon = new ImageIcon(newimg); 
        LoginDetailsIconBtn.setIcon(imageIcon);
        LoginDetailsIconBtn.setText("");
        
        imageIcon = new ImageIcon("../DynamicConAdminApp/src/Resources/Phonebook.png"); 
        image = imageIcon.getImage(); 
        newimg = image.getScaledInstance(80, 80,  java.awt.Image.SCALE_SMOOTH); 
        imageIcon = new ImageIcon(newimg); 
        PhonebookIconBtn.setIcon(imageIcon);
        PhonebookIconBtn.setText("");
        
        imageIcon = new ImageIcon("../DynamicConAdminApp/src/Resources/Calender.png"); 
        image = imageIcon.getImage(); 
        newimg = image.getScaledInstance(80, 80,  java.awt.Image.SCALE_SMOOTH); 
        imageIcon = new ImageIcon(newimg); 
        CalenderIconBtn.setIcon(imageIcon);
        CalenderIconBtn.setText("");
        
        imageIcon = new ImageIcon("../DynamicConAdminApp/src/Resources/Products.png"); 
        image = imageIcon.getImage(); 
        newimg = image.getScaledInstance(80, 80,  java.awt.Image.SCALE_SMOOTH); 
        imageIcon = new ImageIcon(newimg); 
        ProductsIconBtn.setIcon(imageIcon);
        ProductsIconBtn.setText("");
        
        imageIcon = new ImageIcon("../DynamicConAdminApp/src/Resources/Quotations.png"); 
        image = imageIcon.getImage(); 
        newimg = image.getScaledInstance(80, 80,  java.awt.Image.SCALE_SMOOTH); 
        imageIcon = new ImageIcon(newimg); 
        QuotationsIconBtn.setIcon(imageIcon);
        QuotationsIconBtn.setText("");
    }
    
    public void setBackground(){
        JLabel backgroundLbl = new JLabel();
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(Home.class.getResource("/Resources/Pic1.jpg")).getImage().getScaledInstance(1360, 768, java.awt.Image.SCALE_SMOOTH)));
    }
    
    class Listener implements ActionListener{    
        public void actionPerformed(ActionEvent a) {
            Calendar rightNow = Calendar.getInstance();   
            int Hour = rightNow.get(Calendar.HOUR_OF_DAY);
            int Min = rightNow.get(Calendar.MINUTE);
            int Sec = rightNow.get(Calendar.SECOND);
            int Day = rightNow.get(Calendar.DAY_OF_MONTH);
            int Year = rightNow.get(Calendar.YEAR);
            String Month = MonthsArr [rightNow.get(Calendar.MONTH)];
            TimeLbl.setText(String.format("%02d", Hour) + ":" + String.format("%02d", Min) + ":" + String.format("%02d", Sec));
            DateLbl.setText(Day + " " + Month + " " + Year);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TimeLbl = new javax.swing.JLabel();
        DateLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        UsernameLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LoginDetailsIconBtn = new javax.swing.JButton();
        PhonebookIconBtn = new javax.swing.JButton();
        CalenderIconBtn = new javax.swing.JButton();
        ProductsIconBtn = new javax.swing.JButton();
        QuotationsIconBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        hideBtn = new javax.swing.JButton();

        setResizable(false);

        TimeLbl.setBackground(new java.awt.Color(0, 0, 0));
        TimeLbl.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        TimeLbl.setText("12:00:00");

        DateLbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        DateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DateLbl.setText("31 December 2015");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Log-In");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Details");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Phonebook");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Calender");

        UsernameLbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        UsernameLbl.setForeground(new java.awt.Color(0, 0, 0));
        UsernameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernameLbl.setText("Username");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Products");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Quotaions");

        LoginDetailsIconBtn.setBackground(new java.awt.Color(51, 51, 51));
        LoginDetailsIconBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LoginDetailsIconBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginDetailsIconBtn.setText("LoginDetailsIcon");
        LoginDetailsIconBtn.setOpaque(false);
        LoginDetailsIconBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginDetailsIconBtnActionPerformed(evt);
            }
        });

        PhonebookIconBtn.setBackground(new java.awt.Color(51, 51, 51));
        PhonebookIconBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PhonebookIconBtn.setForeground(new java.awt.Color(255, 255, 255));
        PhonebookIconBtn.setText("PhonebookIcon");
        PhonebookIconBtn.setOpaque(false);
        PhonebookIconBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonebookIconBtnActionPerformed(evt);
            }
        });

        CalenderIconBtn.setBackground(new java.awt.Color(51, 51, 51));
        CalenderIconBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        CalenderIconBtn.setForeground(new java.awt.Color(255, 255, 255));
        CalenderIconBtn.setText("CalenderIcon");
        CalenderIconBtn.setOpaque(false);
        CalenderIconBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalenderIconBtnActionPerformed(evt);
            }
        });

        ProductsIconBtn.setBackground(new java.awt.Color(51, 51, 51));
        ProductsIconBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        ProductsIconBtn.setForeground(new java.awt.Color(255, 255, 255));
        ProductsIconBtn.setText("ProductsIcon");
        ProductsIconBtn.setOpaque(false);
        ProductsIconBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsIconBtnActionPerformed(evt);
            }
        });

        QuotationsIconBtn.setBackground(new java.awt.Color(51, 51, 51));
        QuotationsIconBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        QuotationsIconBtn.setForeground(new java.awt.Color(255, 255, 255));
        QuotationsIconBtn.setText("QuotationsIcon");
        QuotationsIconBtn.setOpaque(false);
        QuotationsIconBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuotationsIconBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(51, 51, 51));
        exitBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit Program");
        exitBtn.setOpaque(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        hideBtn.setBackground(new java.awt.Color(51, 51, 51));
        hideBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        hideBtn.setForeground(new java.awt.Color(255, 255, 255));
        hideBtn.setText("Hide Program");
        hideBtn.setOpaque(false);
        hideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(UsernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                        .addComponent(hideBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimeLbl)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DateLbl)
                                .addGap(9, 9, 9)))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addComponent(LoginDetailsIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(PhonebookIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CalenderIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductsIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuotationsIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(UsernameLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(TimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DateLbl))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LoginDetailsIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PhonebookIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addGap(25, 25, 25)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(CalenderIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(ProductsIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(QuotationsIconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9))))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginDetailsIconBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginDetailsIconBtnActionPerformed

    }//GEN-LAST:event_LoginDetailsIconBtnActionPerformed

    private void PhonebookIconBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonebookIconBtnActionPerformed
        
    }//GEN-LAST:event_PhonebookIconBtnActionPerformed

    private void CalenderIconBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalenderIconBtnActionPerformed
        new Calender(con).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CalenderIconBtnActionPerformed

    private void ProductsIconBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsIconBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductsIconBtnActionPerformed

    private void QuotationsIconBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuotationsIconBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuotationsIconBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?",null, JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void hideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideBtnActionPerformed
        this.hide();
    }//GEN-LAST:event_hideBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalenderIconBtn;
    private javax.swing.JLabel DateLbl;
    private javax.swing.JButton LoginDetailsIconBtn;
    private javax.swing.JButton PhonebookIconBtn;
    private javax.swing.JButton ProductsIconBtn;
    private javax.swing.JButton QuotationsIconBtn;
    private javax.swing.JLabel TimeLbl;
    private javax.swing.JLabel UsernameLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton hideBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
